/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#ffffff',
        'surface-dim': '#f1f5f9',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#1e293b',
        'inverse-on-surface': '#f8fafc',
        outline: '#94a3b8',
        'outline-variant': '#e2e8f0',
        'surface-tint': '#4f46e5',
        'surface-variant': '#f1f5f9',
        primary: '#4f46e5',
        'on-primary': '#ffffff',
        'primary-container': '#818cf8',
        'on-primary-container': '#e0e7ff',
        'inverse-primary': '#c7d2fe',
        secondary: '#0f172a',
        'on-secondary': '#ffffff',
        'secondary-container': '#1e293b',
        'on-secondary-container': '#f8fafc',
        tertiary: '#0d9488',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#14b8a6',
        'on-tertiary-container': '#ccfbf1',
        error: '#ef4444',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#991b1b',
        'primary-fixed': '#e0e7ff',
        'primary-fixed-dim': '#c7d2fe',
        'on-primary-fixed': '#312e81',
        'on-primary-fixed-variant': '#4338ca',
        'secondary-fixed': '#f1f5f9',
        'secondary-fixed-dim': '#cbd5e1',
        'on-secondary-fixed': '#0f172a',
        'on-secondary-fixed-variant': '#1e293b',
        'tertiary-fixed': '#ccfbf1',
        'tertiary-fixed-dim': '#99f6e4',
        'on-tertiary-fixed': '#115e59',
        'on-tertiary-fixed-variant': '#134e4a',
        background: '#f8fafc',
        'on-background': '#0f172a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.75', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '4px',
        xs: '0.5rem',
        sm: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'max-width-content': '1280px',
      },
    },
  },
  plugins: [],
}
